### ISSUE TITLE
Pr1 : La funcion listaPokemonDe_ es levemente ineficaz

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#12]
listaPokemonDe_ unEntrenador = (pokemon1(unEntrenador) : []) ++ (pokemon2(unEntrenador) : [])

Estas usando dos listas de forma innecesarias. Intenta usar solamente una.

**Comment by IvanRod1** [comment]
Solucionado

**Comment by JuanIgnGarcia** [comment]
Esta bien. Pero ahora hay paréntesis de mas
