### ISSUE TITLE
Pr.2:  lasDeLongitudMayorA se podria mejorar 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#21]
lasDeLongitudMayorA :: Int -> [[a]] -> [[a]]
lasDeLongitudMayorA b [] = []
lasDeLongitudMayorA b (l:ls) = if longitud l > b
                               then [l] ++ lasDeLongitudMayorA b ls  --> Por qué lo pones en una lista y usas ++ ? 
                               else lasDeLongitudMayorA b ls

**Comment by IvanRod1** [comment]
Solucionado, error de concepto

**Comment by IvanRod1** [comment]
lasDeLongitudMayorA :: Int -> [[a]] -> [[a]]
lasDeLongitudMayorA b [] = []
lasDeLongitudMayorA b (l:ls) = if longitud l > b
                               then l : lasDeLongitudMayorA b ls
                               else lasDeLongitudMayorA b ls
