### ISSUE TITLE
Pr.2: la función zipMaximos no es correcta

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#22]
El máximo entre algo y nada es algo

**Comment by IvanRod1** [comment]
Solucionado

**Comment by IvanRod1** [comment]
zipMaximos :: [Int] -> [Int] -> [Int]
zipMaximos [] [] = [] 
zipMaximos a [] = a
zipMaximos [] b = b
zipMaximos (x:xs) (y:ys) = elMayorDe x y : zipMaximos xs ys

**Comment by JuanIgnGarcia** [comment]
El caso zipMaximos [] [] = []  esta de mas.   Imagina que no tenes esa linea de código y haces zipMaximos [] [], Entras a la pirmera linea que seria zipMaximos a [] = a  machea y devuelve a que seria [ ]

**Comment by IvanRod1** [comment]
Arreglado
