### ISSUE TITLE
Pr.2: la función sinLosPrimeros no es correcta

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#24]
sinLosPrimeros :: Int -> [a] -> [a]
sinLosPrimeros _ [ ] = [ ]
sinLosPrimeros 0 a = a                   --> Podrías usar xs en ves de  usar a
sinLosPrimeros n (x:xs) = if (n <= 0)    ---> Contemplas los números negativos (no es necesario)
                          then x : sinLosPrimeros n xs
                          else sinLosPrimeros (n - 1) xs

**Comment by IvanRod1** [comment]
Solucionado

**Comment by IvanRod1** [comment]
sinLosPrimeros :: Int -> [a] -> [a]
sinLosPrimeros _ [] = []
sinLosPrimeros 0 (_:xs) = xs
sinLosPrimeros n (x:xs) = if (n == 0)
                          then x : sinLosPrimeros n xs
                          else sinLosPrimeros (n - 1) xs

**Comment by JuanIgnGarcia** [comment]
sinLosPrimeros :: Int -> [a] -> [a]
sinLosPrimeros _ [] = []
sinLosPrimeros 0 (_:xs) = xs  --> Perdes un elemento 
sinLosPrimeros n (x:xs) = if (n == 0)  ---> Contemplas otra vez el caso que n sea 0 
            then x : sinLosPrimeros n xs
           else sinLosPrimeros (n - 1) xs

**Comment by IvanRod1** [comment]
sinLosPrimeros :: Int -> [a] -> [a]
sinLosPrimeros _ [] = []
sinLosPrimeros 0 xs = xs
sinLosPrimeros n (x:xs) = if n == 0    <- Esta parte no la entiendo,  vos decís que el if esta mal o la condición es errónea?                 
                          then x : sinLosPrimeros n xs
                          else sinLosPrimeros (n - 1) xs

**Comment by IvanRod1** [comment]
sinLosPrimeros :: Int -> [a] -> [a]
sinLosPrimeros _ [] = []
sinLosPrimeros 0 xs = xs
sinLosPrimeros n (x:xs) = if  n > 0
                          then sinLosPrimeros (n - 1) xs
                          else xs
Hola, rehíce la función después de que se me viniera una idea haciendo otro ejercicio
