### ISSUE TITLE
Pr.2: la función mayoresA no es totalmente correcta

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#25]
mayoresA :: Int -> [Persona] -> [Persona]
mayoresA 0 a = a  --> caso de mas (Podría haber un recién nacido) 
mayoresA _ [] = []
mayoresA n (x:xs) = if edad (x) >= n     --> ¿Por qué usas paréntesis en x ?  ¿30  es mayor que 30 ?
                    then x : mayoresA n xs
                    else mayoresA n xs

**Comment by IvanRod1** [comment]
Solucionado

**Comment by JuanIgnGarcia** [comment]
mayoresA 32 [pepe,pola]  --> Que debería dar ?

pepe = P "pepe" 32
pola = P "polaco" 23

**Comment by IvanRod1** [comment]
Si respeto el concepto de mayor, la función debería devolver una lista vacía

mayoresA :: Int -> [Persona] -> [Persona]
mayoresA _ [] = []
mayoresA n (x:xs) = if edad x > n     <- saque el >= y puse > . Recién lo cambié
                    then x : mayoresA n xs
                    else mayoresA n xs
