### ISSUE TITLE
Pr 2 : La función cuantosDeTipo_De_LeGananATodosLosDe_  no es correcta

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#27]
Para que un pokemon cuente debe ganarle a todos del rival no solamente a uno.

**Comment by IvanRod1** [comment]
Primero, hice una funcion que dado un pokemon y una lista de pokemones, que indica si ese pokemon dado les gana a todos los pokemones de la lista dada.

pokemonContraListaDePokemones :: Pokemon -> [Pokemon] -> Bool
--Funcion para indicar si el pokemon dado, le gana a todos los pokemon de la lista de pokemones
pokemonContraListaDePokemones p [] = True
pokemonContraListaDePokemones  p (x:xs) = tipoDePokemonLeGanaA (tipo p) (tipo x) && pokemonContraListaDePokemones p xs

Segundo, hice otra función que tome dos listas de pokemones, que nos da una lista de pokemones de la primera lista que les ganaron a todos los pokemones de la segunda lista

pokemonesDe_QueGanaronContraTodosLosPokemonesDe_:: [Pokemon] -> [Pokemon] -> [Pokemon]
-- Dado una dos listas de pokemon, devuelve una lista de pokemon de la primera lista de los cuales ganaron todas las peleas contra los pokemon de la segunda lista de pokemon
pokemonesDe_QueGanaronContraTodosLosPokemonesDe_ [] _ = []
pokemonesDe_QueGanaronContraTodosLosPokemonesDe_ _ [] = []
pokemonesDe_QueGanaronContraTodosLosPokemonesDe_ (x:xs) lp = if pokemonContraListaDePokemones x lp
                                                                 then x : pokemonesDe_QueGanaronContraTodosLosPokemonesDe_ xs lp
                                                                 else pokemonesDe_QueGanaronContraTodosLosPokemonesDe_ xs lp 

Tercero, hice la función pedida cuantosDeTipo_De_LeGananATodosLosDe_ , esta función utiliza la función que me devuelve los pokemones que ganaron las peleas, filtro los pokemones por el tipo dado, y a esa lista, le cuento los pokemones que haya con la función longitud

cuantosDeTipo_De_LeGananATodosLosDe_ tp ep1 ep2 = longitud (pokemonesDelTipo_En_ tp (pokemonesDe_QueGanaronContraTodosLosPokemonesDe_ (listPokemon ep1) (listPokemon ep2)))
