### ISSUE TITLE
Pr.2 : En la función hay miedo al booleano tienePokemonTipo 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#28]
tienePokemonTipo :: TipoDePokemon -> [Pokemon] -> Bool
tienePokemonTipo tp [] = False
tienePokemonTipo tp (x:xs) = if comparadorDeTiposDePokemon (tipo x) tp
                              then True   ---> Miedo al bool
                              else tienePokemonTipo tp xs

**Comment by IvanRod1** [comment]
tienePokemonTipo :: TipoDePokemon -> [Pokemon] -> Bool
tienePokemonTipo tp [] = False
tienePokemonTipo tp (x:xs) = comparadorDeTiposDePokemon (tipo x) tp || tienePokemonTipo tp xs 

Lo solucione de esa manera
