### ISSUE TITLE
Pr.2: En perteneceAlRol hay miedo al Booleano

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#29]
perteneceAlRol :: Proyecto -> [Rol] -> Bool 
-- Indica si el proyecto dado, pertenece a algun rol dentro de la lista
perteneceAlRol p [] = False
perteneceAlRol p (x:xs) = if ((nombreProyecto p) == nombreProyecto (proyectoDeUnRol x))  --> usas paréntesis de mas 
                          then True   --> Miedo al bool
                          else perteneceAlRol p xs

**Comment by IvanRod1** [comment]
perteneceAlRol :: Proyecto -> [Rol] -> Bool 
-- Indica si el proyecto dado, pertenece a algun rol dentro de la lista
perteneceAlRol p [] = False
perteneceAlRol p (x:xs) = nombreProyecto p == nombreProyecto (proyectoDeUnRol x) || perteneceAlRol p xs

Lo volví a hacer de esa manera de esa manera
