### ISSUE TITLE
Pr.2: En rolesDondeLosProyectos_EstanPresentes  estas perdiendo elementos

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#30]
rolesDondeLosProyectos_EstanPresentes (x:xs) (y:ys) = 
          estaElProyectoEnLaListaDeRoles x ys : rolesDondeLosProyectos_EstanPresentes xs ys   --->  donde esta y?

**Comment by IvanRod1** [comment]
Solucionado
