### ISSUE TITLE
Pr.3: Sintaxis incorrecta

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#32]
NO se debe subir código a un repositorio (en branch master) SI NO es ejecutable. Debe PROBARSE el código antes de hacer push.

**Comment by IvanRod1** [comment]
Ok, lo voy a tener en cuenta, lo subía a esta branch para tenerlo cuando voy a clase presencial. Voy a usar otra personal para guardar mis trabajos sin terminar
