### ISSUE TITLE
Pr.1: Hay "miedo al booleano" en la función negar 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#4]
negar :: Bool -> Bool
negar True = False
negar False = True ---> Si no es True que puede ser ?

**Comment by IvanRod1** [comment]
Ya lo arreglé, no me había dado cuenta

**Comment by IvanRod1** [comment]
negar :: Bool -> Bool
negar True = False
negar _ = True
