### ISSUE TITLE
Pr.1: La función yTambien hace doble PM

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#5]
Siempre que se pueda resolver una función analizando un único parámetro, es mejor hacerlo así. Analizar más de un parámetro agrega complejidad y permite que sea fácil olvidar casos.

**Comment by IvanRod1** [comment]
Arreglado

**Comment by IvanRod1** [comment]
yTambien :: Bool -> Bool -> Bool
yTambien p q =
     case p of
          True -> q 
          _ -> False

**Comment by JuanIgnGarcia** [comment]
La solución propuesta es correcta pero en esta materia se pide una solución con PM

**Comment by IvanRod1** [comment]
yTambien :: Bool -> Bool -> Bool
yTambien False _ = False
yTambien _  False = False
yTambien _ _ = True

seria algo así?, la verdad me confunde porque pienso que al agregar los dos parámetros que tiene la función siento que hago doble PM y eso dijeron que no se puede en este ejercicio

**Comment by JuanIgnGarcia** [comment]
Tiene miedo al booleano
yTambien :: Bool -> Bool -> Bool
yTambien False _ = False  --> Si el primer parámetro es False da False 
yTambien _ False = False --> Si el primer parámetro no es False (Debe ser True por descarte) mira el segundo y si es False da False 
yTambien _ _ = True --> si te fijas  este caso mira el segundo y si es True da True. Las segunda y 3 linea miran los casos de yTambien  True b (b siendo otro booleano) 

Ya resolviste este ejercicio pero sin usando PM. Si entendés lo que hiciste anteriormente en  (código que dejo abajo) lo tendrías que poder resolverlo rápidamente :
yTambien p q =
   case p of
        True -> q
         _ -> False

**Comment by IvanRod1** [comment]
ahí lo modifique
