### ISSUE TITLE
Pr.1: Hay "miedo al booleano" en la función oBien

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#6]
Básicamente, preguntás si algo es True para devolver True y cuando no es True devolvés

**Comment by IvanRod1** [comment]
Arreglado, creo que me paso algo similar que con el ejercicio de la conjunción

**Comment by IvanRod1** [comment]
oBien :: Bool -> Bool -> Bool
oBien p q =
     case p of
          False -> q
          guionbajo -> True
--Tuve que poner guionbajo porque github me lo toma como si quisiera poner cursiva

**Comment by JuanIgnGarcia** [comment]
La solución propuesta es correcta pero en esta materia se pide una solución con PM

**Comment by JuanIgnGarcia** [comment]
Lo mismo que yTambien

**Comment by IvanRod1** [comment]
Ahí lo modifique
