### ISSUE TITLE
Pr.1: Te falta la funcion laQueEsMayor 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#8]
laQueEsMayor :: Persona -> Persona -> Persona

**Comment by IvanRod1** [comment]
Agregado, me lo pase por arriba ese ejercicio

**Comment by IvanRod1** [comment]
laQueEsMayor :: Persona -> Persona -> Persona
laQueEsMayor persona1 persona2 = if esMayorQueLaOtra persona1 persona2
                                 then persona1
                                 else persona2
