### ISSUE TITLE
Pr.1: Hay paréntesis de más en la función superaA 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [IvanRod1/EstrD2023s1#9]
superaA unPokemon otroPokemon = tipoDePokemonLeGanaA (tipo(unPokemon)) (tipo(otroPokemon))
                                                       =  tipoDePokemonLeGanaA (tipo unPokemon) (tipo otroPokemon)

No hace falta poner un elemento solo entre paréntesis, ya que los paréntesis se utilizan para agrupar varios elementos

**Comment by IvanRod1** [comment]
Solucionado
